# Generated by Django 3.1.4 on 2020-12-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_auto_20201203_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='../media/default_user.png', upload_to=''),
        ),
    ]
