# Generated by Django 3.1.4 on 2020-12-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201213_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='desciption',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
    ]
