# Generated by Django 3.1.4 on 2020-12-14 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20201214_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='textField',
            new_name='content',
        ),
    ]
